### ISSUE TITLE
Problem Installing hdp

### ISSUE THREAD

**Issue by imk1** [blei-lab/hdp#4]
I am trying to install hdp, and I get this error:

In file included from state.h:4:0,
                 from state.cpp:1:
corpus.h: In constructor ‘document::document()’:
corpus.h:18:17: error: ‘NULL’ was not declared in this scope
         words = NULL;
                 ^
corpus.h: In destructor ‘document::~document()’:
corpus.h:34:22: error: ‘NULL’ was not declared in this scope
         if (words != NULL)
                      ^
In file included from state.cpp:1:0:
state.h: At global scope:
state.h:146:63: error: ‘NULL’ was not declared in this scope
                                      hdp_state * target_state=NULL);
                                                               ^
In file included from state.h:4:0,
                 from hdp.h:4,
                 from hdp.cpp:1:
corpus.h: In constructor ‘document::document()’:
corpus.h:18:17: error: ‘NULL’ was not declared in this scope
         words = NULL;
                 ^
corpus.h: In destructor ‘document::~document()’:
corpus.h:34:22: error: ‘NULL’ was not declared in this scope
         if (words != NULL)
                      ^
In file included from hdp.h:4:0,
                 from hdp.cpp:1:
state.h: At global scope:
state.h:146:63: error: ‘NULL’ was not declared in this scope
                                      hdp_state * target_state=NULL);
                                                               ^
hdp.cpp: In member function ‘void hdp::run(const char*)’:
hdp.cpp:147:97: error: call to ‘double hdp_state::split_sampling(int, int, int, int, int, hdp_state*)’ uses the default argument for parameter 6, which is not yet defined
                     double prob_split = proposed_state->split_sampling(num_scans, d0, d1, t0, t1);
                                                                                                 ^
Makefile:13: recipe for target 'hdp' failed
make[1]: *** [hdp] Error 1
make[1]: Leaving directory '/srv/scratch/shared/surya/imk1/TFBindingPredictionProject/src/hdp/hdp'
Makefile:4: recipe for target 'make_all' failed
make: *** [make_all] Error 2

I installed the latest version of gsl, and I think that I updated the Makefiles in hdp and hdp-faster correctly.  Do you know what might be causing this problem?

Thanks so much!

**Comment by imk1** [comment]
It looks like adding #include \<cstddef\> to corpus.h solved the problem.

**Comment by jaanaltosaar** [comment]
Cool! Can you submit a pull request for this please?

**Comment by imk1** [comment]
Done!
https://github.com/blei-lab/hdp/pull/5
